steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/app-images/backend:${SHORT_SHA}'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/app-images/backend:staging-latest'
      - './app/backend'

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/app-images/backend:${SHORT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/app-images/backend:staging-latest'

  # Step 3: Run database migrations (Staging)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs create db-migrate-staging-${SHORT_SHA} \
          --image=asia-northeast1-docker.pkg.dev/${PROJECT_ID}/app-images/backend:${SHORT_SHA} \
          --region=asia-northeast1 \
          --vpc-connector=vpc-connector \
          --service-account=cloud-run-staging@${PROJECT_ID}.iam.gserviceaccount.com \
          --set-env-vars="DB_HOST=10.81.0.10,DB_PORT=5432,DB_NAME=pm_app,DB_USER=app_user" \
          --set-secrets="DB_PASSWORD=db-password-staging:latest" \
          --command=node \
          --args=src/migrate.js \
          --max-retries=3 || true
        
        gcloud run jobs execute db-migrate-staging-${SHORT_SHA} \
          --region=asia-northeast1 \
          --wait
        
        gcloud run jobs delete db-migrate-staging-${SHORT_SHA} \
          --region=asia-northeast1 \
          --quiet || true

  # Step 4: Deploy to Cloud Run (Staging)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'app-staging'
      - '--image=asia-northeast1-docker.pkg.dev/${PROJECT_ID}/app-images/backend:${SHORT_SHA}'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--vpc-connector=vpc-connector'
      - '--service-account=cloud-run-staging@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-env-vars=DB_HOST=10.81.0.10,DB_PORT=5432,DB_NAME=pm_app,DB_USER=app_user,NODE_ENV=staging'
      - '--set-secrets=DB_PASSWORD=db-password-staging:latest,FIREBASE_SERVICE_ACCOUNT=firebase-service-account-dev:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1200s
